env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  class-methods-use-this: 0
  no-console: 0
  no-await-in-loop: 0
  global-require: 0
  no-underscore-dangle: 0
ignorePatterns:
  - ".vscode/**"
  - "features/**"
  - "venv/**"